### ISSUE TITLE
Meta Info not Updated for Keep Alive components

### ISSUE THREAD

**Issue by po-trottier** [troxler/vue-headful#12] opened 2019-08-19 15:27 UTC
When a component is wrapped in a keep-alive tag (<keep-alive><my-component /></keep-alive>) the Meta Info for the page is not updated after the initial load, as the created hook is not being called. 

Repro steps:
1) Create a vue app with a Vue Router
2) Create 2 routes
3) Make 1 of these routes keep-alive
4) Set a different Meta Title for each route
5) Start the app
6) Navigate to the Keep-Alive page. The title will be OK
7) Navigate to the regular page. The title will be OK
8) Go back to the Keep-Alive page. The title will NOT BE OK.

The title should be updated on focus/beforeEachRoute, not on created.

**Comment by troxler** [comment] 2019-09-10 09:46
Thanks for the bug report. Could you provide a code example to reproduce the issue?

**Comment by po-trottier** [comment] 2019-09-10 16:42
@troxler 

There you go:
https://github.com/po-trottier/vue-headful-example

Steps:
1) npm install
2) npm run serve
3) go to the about page
4) come back to the home page (by using the navigation bar)
5) Notice the title is still that of the About page

**Comment by troxler** [comment] 2019-09-29 17:31
Thanks for that. It seems that it can be solved using the `activated` hook. See https://github.com/troxler/vue-headful/commit/db4aa5ede5052b15a408acc32e46b1b65469218a. I will do some more testing and make a release if it works out well.

**Comment by positivethinking639** [comment] 2019-11-30 03:14
@troxler Is this method really useful for SEO? if I right-click on my website and select `View Page Source`, I see the title, description, keywords don't change. I look doubtful this way is correct

**Comment by troxler** [comment] 2019-11-30 11:39
@positivethinking639 Are you referring to keep-alive components? This issue is still open and they are not supported yet. Or are you referring to vue-headful in general? Are you using prerendering or server-side rendering?

**Comment by positivethinking639** [comment] 2019-11-30 12:14
@troxler I'm sorry. I just want to make sure.  I referring to vue-headful in general. I don't use SSR. I think using vue-headful, it already supports SEO. Because vue-headful exist meta tags. So I think vue-headful had support SEO

**Comment by troxler** [comment] 2019-11-30 18:42
@positivethinking639 A quick search on this topic lead me [to this site](https://www.onely.com/blog/ultimate-guide-javascript-seo/) which seems to explain the limitations of JavaScript regarding SEO (I only very quickly skimmed through it though). In short: If you want to be sure that your JavaScript page is indexed properly, you have to use either prerendering or SSR.

**Comment by positivethinking639** [comment] 2019-11-30 23:29
So there is no proof if using vue-headful is really useful for SEO?

**Comment by po-trottier** [comment] 2019-11-30 23:34
Yes, the plugin indeed helps for SEO. I use it in with Rendertron to serve dynamically rendered content (SSR for Crawlers, and CSR for regular clients) and my pages are index as expected, with proper meta info and all.

**Comment by positivethinking639** [comment] 2019-12-01 00:04
So are you saying that if we only use vue-headful for our vue project,
isn't that useful for SEO? We have to collaborate it with the SSR package
to be useful for SEO. Right?

**Comment by po-trottier** [comment] 2019-12-01 00:06
Yes, web crawlers, in general, don't play nice with SPAs. You can read about it [here](https://developers.google.com/search/docs/guides/dynamic-rendering)

**Comment by positivethinking639** [comment] 2019-12-01 00:29
Okay thanks. Maybe I will use this docs https://ssr.vuejs.org/ to implement
ssr

**Comment by troxler** [comment] 2019-12-30 19:42
Fixed in [version 2.1](https://github.com/troxler/vue-headful/releases/tag/v2.1.0).

**Closed as completed by troxler** 2019-12-30 19:42 UTC
